/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layouts/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layouts/AppHeader.vue')['default']
    AuthCheckMail: typeof import('./components/authForms/AuthCheckMail.vue')['default']
    AuthCodeVerification: typeof import('./components/authForms/AuthCodeVerification.vue')['default']
    AuthForgotPwd: typeof import('./components/authForms/AuthForgotPwd.vue')['default']
    AuthLogin: typeof import('./components/authForms/AuthLogin.vue')['default']
    AuthRegister: typeof import('./components/authForms/AuthRegister.vue')['default']
    AuthResetPwd: typeof import('./components/authForms/AuthResetPwd.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
