/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/LoginPage': RouteRecordInfo<'/auth/LoginPage', '/auth/LoginPage', Record<never, never>, Record<never, never>>,
    '/auth/RegisterPage': RouteRecordInfo<'/auth/RegisterPage', '/auth/RegisterPage', Record<never, never>, Record<never, never>>,
    '/auth/ResetPwd': RouteRecordInfo<'/auth/ResetPwd', '/auth/ResetPwd', Record<never, never>, Record<never, never>>,
    '/error/Error404Page': RouteRecordInfo<'/error/Error404Page', '/error/Error404Page', Record<never, never>, Record<never, never>>,
    '/error/Error500Page': RouteRecordInfo<'/error/Error500Page', '/error/Error500Page', Record<never, never>, Record<never, never>>,
  }
}
